version: 2.1

orbs:
  slack: circleci/slack@5.2.3
  scotty-orb: cci-releng/scotty-orb@0.0.12

executors:
  ccc:
    docker:
      - image: circleci/command-convenience:0.1
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD

workflows:
  my-workflow:
    jobs:
      - image:
          name: "scan-<< matrix.service_path >>"
          command: scan
          matrix:
            alias: scan
            parameters:
              service_path: [postgres/13, postgres/18, rabbitmq/3, redis/6, mongodb/7]
          context: "org-global"
          filters:
            branches:
              ignore:
                - main
                - /^server-\d\..+/
      - image:
          name: "publish-<< matrix.service_path >>"
          command: publish
          matrix:
            alias: publish
            parameters:
              # TODO: Publish and promote postgres/18 after ONPREM-2563
              service_path: [postgres/13, rabbitmq/3, redis/6, mongodb/7]
          context: "org-global"
          filters: &publish_filters
            branches:
              only:
                - main
                - /^server-\d\..+/
      - scotty-orb/test-in-server-and-promote:
          name: test-in-server-and-promote
          context: ["org-global", github-readonly]
          requires:
            - publish
          promotion_component_list: "circleci/server-mongodb circleci/server-postgres circleci/server-rabbitmq circleci/server-redis"
          filters: *publish_filters

jobs:
  image:
    executor: ccc
    parameters:
      service_path:
        type: string
      command:
        type: enum
        enum: [scan, publish]
    steps:
      - setup_remote_docker
      - checkout
      - run:
          pwd: << parameters.service_path >>
          name: << parameters.command >>-server-<< parameters.service_path >>
          environment:
            DOCKERFILE_PATH: Dockerfile
            DOCKER_REGISTRY: dockerhub
          command: |
            service="$(dirname << parameters.service_path >>)"
            version="$(grep -m1 "^ARG ${service^^}_VERSION=" Dockerfile | cut -d= -f2)"

            NAME="server-${service}" \
            MAJOR_VERSION="$(echo "${version}" | cut -d. -f1,2)" \
            << parameters.command >>
      - slack/notify:
          channel: server-alerts
          branch_pattern: main, server-[0-9]\.[0-9]+
          event: fail
          template: basic_fail_1
