{{- /*
Copyright VMware, Inc.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.rbac.create }}
kind: Role
apiVersion: {{ include "common-v2.capabilities.rbac.apiVersion" . }}
metadata:
  name: {{ printf "%s-endpoint-reader" (include "common-v2.names.fullname" .) }}
  namespace: {{ include "common-v2.names.namespace" . | quote }}
  labels: {{- include "common-v2.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common-v2.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
{{- end }}
